---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-text-mining/resources/d9pwm) course resource._

---

# Assignment 1

In this assignment, you'll be working with messy medical data and using regex to extract relevant infromation from the data. 

Each line of the `dates.txt` file corresponds to a medical note. Each note has a date that needs to be extracted, but each date is encoded in one of many formats.

The goal of this assignment is to correctly identify all of the different date variants encoded in this dataset and to properly normalize and sort the dates. 

Here is a list of some of the variants you might encounter in this dataset:
* 04/20/2009; 04/20/09; 4/20/09; 4/3/09
* Mar-20-2009; Mar 20, 2009; March 20, 2009;  Mar. 20, 2009; Mar 20 2009;
* 20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009
* Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009
* Feb 2009; Sep 2009; Oct 2010
* 6/2008; 12/2009
* 2009; 2010

Once you have extracted these date patterns from the text, the next step is to sort them in ascending chronological order accoring to the following rules:
* Assume all dates in xx/xx/xx format are mm/dd/yy
* Assume all dates where year is encoded in only two digits are years from the 1900's (e.g. 1/5/89 is January 5th, 1989)
* If the day is missing (e.g. 9/2009), assume it is the first day of the month (e.g. September 1, 2009).
* If the month is missing (e.g. 2010), assume it is the first of January of that year (e.g. January 1, 2010).
* Watch out for potential typos as this is a raw, real-life derived dataset.

With these rules in mind, find the correct date in each note and return a pandas Series in chronological order of the original Series' indices.

For example if the original series was this:

    0    1999
    1    2010
    2    1978
    3    2015
    4    1985

Your function should return this:

    0    2
    1    4
    2    0
    3    1
    4    3

Your score will be calculated using [Kendall's tau](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), a correlation measure for ordinal data.

*This function should return a Series of length 500 and dtype int.*

In [ ]:
import re

In [ ]:
import pandas as pd

doc = []
with open('dates.txt') as file:
    for line in file:
        doc.append(line)

df = pd.Series(doc)
# df.head(10)

In [1]:
def date_sorter():
    import re
    import pandas as pd
    
    doc = []
    with open('dates.txt') as file:
        for line in file:
            doc.append(line)

    df = pd.Series(doc)
    
    type1 = r'(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})' #dates of type 03/25/93, 3/5/1993....or replace backslash with hyphens
    type2 = r'((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec))[a-z]*[.]?[-/ ](\d{1,2})[a-z{2}]*[,/.]?[- ](\d{2,4})' #dates of type
    # Jan.01,2000 or January/20/2000 or march 20th 1272 or year with two digits or hyphens in place of backslashes or commas
    type3 = r'(\d{1,2})[ -/,.]((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec))[a-z]*[.,]? (\d{2,4})' 
    #of type 20 Jan,2009
    type4 = r'((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec))[a-z]*[,]? (\d{2,4})'  #just years with months
    type5 = r'(\d{1,2})[-/. ](\d{2,4})' # to handle 10/2019, 10 2019, 10.2019...
    type6 = r'\d{4}' #to handle 3002,3721...
    
    
    month_dict = {'Jan': '01', 
                  'Feb': '02' ,
                  'Mar': '03',
                  'Apr':'04',
                  'May':'05',
                  'Jun':'06',
                  'Jul':'07',
                  'Aug':'08',
                  'Sep':'09',
                  'Oct':'10',
                  'Nov':'11',
                  'Dec':'12'}
    
    #we can run a for loop in dates, but as many of the dates will be trapped in first two types, we can be wasting computing power to run the loop
#     string_num = 0
    dates = []
    for string in df:
#         string_num+=1
#         print(string_num)# to know the status of program
        
#         '''04/20/2009'''
        if (re.findall(type1,string)):
            date=list(re.findall(type1,string)[0]) #we might have to run a loop within re,findall() if there were multiple dates in each entry
            if len(date[2])==2: # year
                date[2] ='19'+date[2]
            if len(date[0])==1:   ##date
                date[0] = '0'+ date[0]
            if len(date[1])==1:   #month
                date[1] = '0'+ date[1]
            dates.append(date[2]+date[0]+date[1])
                     
#         '''Mar 22nd, 2009    Mar 22, 2009'''
        elif (re.findall(type2,string)): 
            date=list(re.findall(type2,string)[0])
            if len(date[2])==2: # year
                date[2] ='19'+date[2]
            if len(date[1])==1:  #date
                date[1] = '0'+ date[1]
            date[0] = month_dict[date[0]] #month
            dates.append(date[2]+date[0]+date[1])

#         '''20 March 2009 20 Mar. 2009'''
        elif re.findall(type3,string):
            date=list(re.findall(type3,string)[0])
            if len(date[2])==2: # year
                date[2] ='19'+date[2]
            if len(date[0])==1:  #date
                date[0] = '0'+ date[0]
            date[1] = month_dict[date[1]]
            dates.append(date[2]+date[1]+date[0])

#         '''Sep 2009'''
        elif re.findall(type4,string):
            date=list(re.findall(type4,string)[0])
            date[0] = month_dict[date[0]] #month
            if len(date[1])==2: # year
                date[1] ='19'+date[1]
            dates.append(date[1]+date[0]+'01')

#         '''6/2008'''
        elif re.findall(type5,string):
            date=list(re.findall(type5,string)[0])
            if len(date[0])== 1: #month
                date[0] = '0'+date[0]
            if len(date[1])==2: #year
                date[1] == '19'+date[1]
            dates.append(date[1]+date[0]+'01')

#         '''2010'''
        elif re.findall(type6,string):
            date=(re.findall(type6,string)[0])
            dates.append(date+'01'+'01')

#         '''to check if we were not able to capture any dates'''
        else :
            print(string)
        datesdf = pd.Series(dates)
        datesdf.sort_values(inplace=True)
        result  = pd.Series(datesdf.index)
    
    return result# Your answer here

In [2]:
date_sorter()

0        9
1       84
2        2
3       53
4       28
5      474
6      153
7       13
8      129
9       98
10     111
11     225
12      31
13     171
14     191
15     486
16     335
17     415
18      36
19     405
20     323
21     422
22     375
23     380
24     345
25      57
26     481
27     436
28     104
29     299
      ...
470    243
471    139
472    320
473    383
474    244
475    286
476    480
477    431
478    279
479    198
480    381
481    463
482    366
483    439
484    255
485    401
486    475
487    257
488    152
489    235
490    464
491    253
492    231
493    427
494    141
495    186
496    161
497    413
498    392
499    490
Length: 500, dtype: int64

instead of regular expression commands, can run commands on dataframe itself.using commands like the following  
`df.str.extractall(pattern)`  
`df.apply(function)`  
`df.replace(word1,word2)`

a [solution](https://github.com/bondeanikets/Applied-Text-Mining-in-Python/blob/master/Week%201/Assignment%2B1.ipynb) following that method